name: book_appointment
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  scoped_model:
  paging:
  loadmore:
  flutter_pagination_helper:
  permission_handler: 8.0.1
  flutter_braintree:
  flutter_stripe: 1.3.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_fonts:
  http: 0.12.2
  convert:
  geolocator: 7.1.0
  toast:
  #firebase_core:
  shared_preferences: 0.5.6
  #firebase_messaging:
  email_validator:
  google_maps_flutter:
  url_launcher:
  geocode:
  masked_text_input_formatter:
  cached_network_image:
  image_picker: 0.6.7
  flutter_local_notifications:
  device_info:
  flutter_html:
  #facebook_audience_network:
  #facebook_audience_network:
  dio:
  #google_sign_in:
  dotted_border: ^2.0.0+1
  photo_view: ^0.13.0
  table_calendar: ^3.0.3
  syncfusion_flutter_datepicker: ^19.3.53
  #native_admob_flutter:
  #flutter_login_facebook:
  geocoding: ^2.0.1



dependency_overrides:
#  image_picker_platform_interface: ^1.1.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name:
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/homeScreenImages/
    - assets/moreScreenImages/
    - assets/loginScreenImages/
    - assets/detailScreenImages/
    - assets/specialityScreenImages/
    - assets/makeAppointmentScreenImages/
    #   - images/a_dot_ham.jpeg

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family:
    #Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
